VialidadSystem/Controllers/HomeController.cs
using System.Web.Mvc;
using Vialidad.Common.Models;

namespace VialidadSystem.Controllers
{
    public class HomeController : Controller
    {        
        public ActionResult Index()
        {
            var model = new LoginModel();
            return View(model);
        }

        public ActionResult Login(LoginModel model)
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

VialidadSystem/Controllers/InfraccionsController.cs
using System.Collections.Generic;
using AutoShopSystemManagement.Data.Dtos;
using AutoShopSystemManagement.Data.Entities;
using AutoShopSystemManagement.Data.Repositories.Interfaces;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoShopSystemManagement.Data.Services.Interfaces;

namespace VialidadSystem.Controllers
{
    public class InfraccionsController : Controller
    {
        private readonly IInfraccionRepository _infraccionRepository;
        private readonly ITipoDeInfraccionRepository _tipoDeInfraccionRepository;
        private readonly IEstadosRepository _estadosRepository;
        private readonly IUsosRepository _usosRepository;
        private readonly IVehicleBrandsRepository _vehicleBrandsRepository;
        private readonly IInfractionService _infractionService;

        public InfraccionsController(IInfraccionRepository infraccionRepository, ITipoDeInfraccionRepository tipoDeInfraccionRepository,IEstadosRepository estadosRepository,IUsosRepository usosRepository,IVehicleBrandsRepository vehicleBrandsRepository,IInfractionService infractionService)
        {
            _infraccionRepository = infraccionRepository;
            _tipoDeInfraccionRepository = tipoDeInfraccionRepository;
            _estadosRepository = estadosRepository;
            _usosRepository = usosRepository;
            _vehicleBrandsRepository = vehicleBrandsRepository;
            _infractionService = infractionService;
        }
        [HttpGet]
        public ActionResult AgregarTipoInfraccion()
        {
            var model = new TipoDeInfraccion();
            return View(model);
        }
        [HttpPost]
        public ActionResult AgregarTipoInfraccion(TipoDeInfraccion model)
        {
            _tipoDeInfraccionRepository.AddNewInfractionType(model);
            return RedirectToAction("ListarConceptos");
        }

        [HttpGet]
        public ActionResult ListarConceptos()
        {
            var model = _tipoDeInfraccionRepository.GetAll();
            return View(model);
        }

        [HttpGet]
        public ActionResult CrearInfraccion()
        {
            var model = new CreateInfractionModel
            {
                Infraccion = new Infraccion
                {
                    Persona = new Personas()
                },
                InfraccionTypes = _tipoDeInfraccionRepository.GetAll().ToList(),
                Estados=_estadosRepository.GetAll().ToList(),
                Usos = _usosRepository.GetAll().ToList(),
                VehicleBrands = _vehicleBrandsRepository.GetAll().ToList()
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult CrearInfraccion(CreateInfractionModel model, IEnumerable<HttpPostedFileBase> images)
        {
            var infraccion=_infractionService.CreateNewInfraction(model,images);
            var viewModel = new InfraccionDetailDto
            {
                Infraccion = infraccion,
                Infracciones = GetInfraccionNames(infraccion)
            };
            return View("InfraccionConfirmacion", viewModel);
        }

        public ActionResult InfraccionDetalle(int id)
        {
            var infraccion = _infraccionRepository.Get(id);
            var viewModel = new InfraccionDetailDto
            {
                Infraccion = infraccion,
                Infracciones = GetInfraccionNames(infraccion)
            };
            return View("InfraccionConfirmacion", viewModel);
        }

        private List<string> GetInfraccionNames(Infraccion infraccion)
        {
            if (infraccion?.Detalles == null) return null;

            return infraccion.Detalles.Select(i => _tipoDeInfraccionRepository.Get(i.TipoDeInfraccionId).TipoDeInfraccionName).ToList();

        }
    }
}

VialidadSystem/Views/Home/About.cshtml
@{
    Layout =  "~/Views/Shared/_LayoutSystem.cshtml";
}
<div class="user-dashboard" >
    <div class="row">
        <input class="form-control" style="display:inline-block;" placeholder="Busqueda" />
        <a href="#/crearInfraccion" class="btn btn-primary" style="display:inline-block;" >Crear Concepto</a>
    </div>
    <div class="row">
        <div class="col-lg-1 col-md-1 col-xs-1"><span class="text-center">No#</span></div>
        <div class="col-lg-6 col-md-6 col-xs-6"><h5 class="text-center">Tipo de Infracción</h5></div>
        <div class="col-lg-2 col-md-2 col-xs-2"><h5 class="text-center">Multiplicador</h5></div>
        <div class="col-lg-2 col-md-2 col-xs-2"><h5 class="text-center">Costo</h5></div>
    </div>
    <div class="row" >
        @*<div class="col-lg-1 col-md-1 col-xs-1"><span class="text-center">{{item.TipoDeInfraccionId}}</span></div>
        <div class="col-lg-6 col-md-6 col-xs-6"><span class="text-center">{{item.TipoDeInfraccionName}}</span></div>
        <div class="col-lg-2 col-md-2 col-xs-2"><spam class="text-center">{{item.Multiplicador}}</spam></div>
        <div class="col-lg-2 col-md-2 col-xs-2"><spam class="text-center">${{item.Costo}}</spam></div>*@
    </div>
</div>

VialidadSystem/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

VialidadSystem/Views/Home/Index.cshtml
@model  Vialidad.Common.Models.LoginModel
<div class="row">
    <div class="container" style="margin-top:40px" ng-controller="navBarController">
        <div class="row">
            <div class="col-sm-6 col-md-4 col-md-offset-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <strong> Ingresa Credenciales</strong>
                    </div>
                    <div class="panel-body">
                        @using (Html.BeginForm("Login", "Home"))
                        {
                            <fieldset>
                                <div class="row">
                                    <div class="center-block">
                                        <img class="profile-img" src="/Content/Images/logotam.png" alt="">
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12 col-md-10  col-md-offset-1 ">
                                        <div class="form-group">
                                            <div class="input-group">
                                                <span class="input-group-addon">
                                                    <i class="glyphicon glyphicon-user"></i>
                                                </span>
                                                @Html.TextBoxFor(x=>x.UserName,new { PlaceHolder="Usuario", @class = "form-control" })                                                
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="input-group">
                                                <span class="input-group-addon">
                                                    <i class="glyphicon glyphicon-lock"></i>
                                                </span>
                                                @Html.PasswordFor(x => x.Password, new { PlaceHolder = "Password", @class = "form-control" })
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <input type="submit" class="btn btn-lg btn-primary btn-block" value="Entrar">
                                        </div>
                                    </div>
                                </div>
                            </fieldset>
                        }

                        <form role="form" ng-submit="LogOn()">
                            
                        </form>
                    </div>
                    <div class="panel-footer ">
                        <a href="#" onClick="">Asi va quedando la aplicacion Marco y Alma</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

VialidadSystem/Views/Infraccions/AgregarTipoInfraccion.cshtml
@model AutoShopSystemManagement.Data.Entities.TipoDeInfraccion

@{
    ViewBag.Title = "AgregarTipoInfraccion";
    Layout = "~/Views/Shared/_LayoutSystem.cshtml";
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<h2>AgregarTipoInfraccion</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.TipoDeInfraccionName, new { PlaceHolder = "Nombre del concepto", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipoDeInfraccionName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Multiplicador, new { PlaceHolder = "Multiplicador", @class = "form-control",Value="" })
                @Html.ValidationMessageFor(model => model.Multiplicador, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="form-group  col-lg-2 col-md-2 col-xs-12">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

VialidadSystem/Views/Infraccions/CrearInfraccion.cshtml
@model AutoShopSystemManagement.Data.Dtos.CreateInfractionModel

@{
    ViewBag.Title = "CrearInfraccion";
    Layout = "~/Views/Shared/_LayoutSystem.cshtml";
}

<h2>Crear Infraccion</h2>


@using (Html.BeginForm("CrearInfraccion","Infraccions",FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="user-dashboard" >
        <h1>Agente Torres</h1>
        <div class="row">
            <form role="form" ng-submit="onSend()">
                <div class="form-group col-lg-4 col-md-6 col-xs-12">
                    <label>Numero de Placa</label>
                    @Html.TextBoxFor(x=>x.Infraccion.Placa, new {@class= "form-control text-capitalize" })
                    @Html.ValidationMessageFor(x=>x.Infraccion.Placa,"", new { @class = "text-danger" })
                </div>
                <div class="form-group col-lg-4 col-md-6 col-xs-12">
                    <label>Año</label>
                    @Html.TextBoxFor(x=>x.Infraccion.VehicleYear, new {@class= "form-control text-capitalize" ,Value=""})
                    @Html.ValidationMessageFor(x=>x.Infraccion.VehicleYear,"", new { @class = "text-danger" })
                </div>
                <div class="form-group col-lg-4 col-md-6 col-xs-12">
                    <label>Estado</label>
                    @Html.DropDownListFor(m => m.Infraccion.Persona.EstadoLicense, new SelectList(Model.Estados, "Id", "EstadoName"),new{ @class = "form-control" })
                </div>
                <div class="form-group col-lg-6 col-md-6 col-xs-12">
                    <label>Uso</label>
                    <select class="form-control">
                        <option value="0">--Seleccione--</option>
                        @foreach (var e in Model.Usos)
                        {
                            <option value="@e.Id">@e.UsoName</option>
                        }
                    </select>
                </div>
                <div class="form-group col-lg-6 col-md-6 col-xs-12">
                    <label>Color</label>
                    @Html.TextBoxFor(x=>x.Infraccion.VehicleColor,new{ @class = "form-control" })
                    @Html.ValidationMessageFor(x=>x.Infraccion.VehicleColor,"", new { @class = "text-danger" })
                </div>
                <div class="form-group col-lg-6 col-md-6 col-xs-12">
                    <label>Marca del Vehiculo</label>
                    @Html.DropDownListFor(m => m.Infraccion.VehicleBrand, new SelectList(Model.VehicleBrands, "Id", "VehicleBrandName"),new{ @class = "form-control" })
                </div>
                <div class="form-group col-lg-6 col-md-6 col-xs-12">
                    <label>Modelo</label>
                    @Html.TextBoxFor(x=>x.Infraccion.VehicleModel,new{ @class = "form-control" })
                    @Html.ValidationMessageFor(x=>x.Infraccion.VehicleModel,"", new { @class = "text-danger" })

                </div>
                <hr />
                <div class="col-lg-3 col-md-3 col-xs-12 form-group">
                    <label>Licencia No.</label>
                    @Html.TextBoxFor(x=>x.Infraccion.Persona.LicenseNumber,new{ @class = "form-control text-capitalize" })
                    @Html.ValidationMessageFor(x=>x.Infraccion.Persona.LicenseNumber,"", new { @class = "text-danger" })

                </div>
                <div class="col-lg-3 col-md-3 col-xs-12 form-group">
                    <label>Mes</label>
                    <select class="form-control" ng-model="infraction.Mes">
                        <option value="01 ENERO">01 ENERO</option>
                        <option value="02 FEBRERO">02 FEBRERO</option>
                        <option value="03 MARZO">03 MARZO</option>
                        <option value="04 ABRIL">04 ABRIL</option>
                        <option value="05 MAYO">05 MAYO</option>
                        <option value="06 JUNIO">06 JUNIO</option>
                        <option value="07 JULIO">07 JULIO</option>
                        <option value="08 AGOSTO">08 AGOSTO</option>
                        <option value="09 SEPTIEMBRE">09 SEPTIEMBRE</option>
                        <option value="10 OCTUBRE">10 OCTUBRE</option>
                        <option value="11 NOVIEMBRE">11 NOVIEMBRE</option>
                        <option value="12 DICIEMBRE">12 DICIEMBRE</option>
                    </select>
                </div>
                <div class="col-lg-3 col-md-3 col-xs-12 form-group">
                    <label>Estado de Licencia</label>
                    @Html.DropDownListFor(m => m.Infraccion.EstadoId, new SelectList(Model.Estados, "Id", "EstadoName"), new { @class = "form-control" })
                </div>
                <div class="col-lg-3 col-md-3 col-xs-12 form-group">
                    <label>Tipo de Licencia</label>
                    @Html.TextBoxFor(x=>x.Infraccion.Persona.LicenseType,new{ @class = "form-control text-capitalize" })
                    @Html.ValidationMessageFor(x=>x.Infraccion.Persona.LicenseType,"", new { @class = "text-danger" })
                </div>
                <hr />
                <div class="col-lg-3 col-md-3 col-xs-12 form-group">
                    <label>Primer Nombre</label>
                    @Html.TextBoxFor(x=>x.Infraccion.Persona.FirstName,new{ @class="form-control text-capitalize" })
                    @Html.ValidationMessageFor(x => x.Infraccion.Persona.FirstName, "", new { @class = "text-danger" })
                </div>
                <div class="col-lg-3 col-md-3 col-xs-12 form-group">
                    <label>Segundo Nombre</label>
                    @Html.TextBoxFor(x=>x.Infraccion.Persona.MiddleName,new{ @class="form-control text-capitalize" })
                    @Html.ValidationMessageFor(x => x.Infraccion.Persona.MiddleName, "", new { @class = "text-danger" })                
                </div>
                <div class="col-lg-3 col-md-3 col-xs-12 form-group">
                    <label>Apellido Paterno</label>
                    @Html.TextBoxFor(x=>x.Infraccion.Persona.LastName1,new{ @class="form-control text-capitalize" })
                    @Html.ValidationMessageFor(x => x.Infraccion.Persona.LastName1, "", new { @class = "text-danger" })                
                </div>
                <div class="col-lg-3 col-md-3 col-xs-12 form-group">
                    <label>Apellido Materno</label>
                    @Html.TextBoxFor(x=>x.Infraccion.Persona.LastName2,new{ @class="form-control text-capitalize" })
                    @Html.ValidationMessageFor(x => x.Infraccion.Persona.LastName2, "", new { @class = "text-danger" })               
                </div>
                <div class="col-lg-12 col-md-12 col-xs-12 form-group">
                    <label>Domicilio del Conductor</label>
                    @Html.TextBoxFor(x => x.Infraccion.Persona.Direccion, new { @class = "form-control text-capitalize" })
                    @Html.ValidationMessageFor(x => x.Infraccion.Persona.Direccion, "", new { @class = "text-danger" })
                </div>
                <div class="col-lg-6 col-md-6 col-xs-12 form-group">
                    <label>Ubicaion de la Falta</label>
                    @Html.TextBoxFor(x => x.Infraccion.Ubicacion, new { @class = "form-control text-capitalize" })
                    @Html.ValidationMessageFor(x => x.Infraccion.Ubicacion, "", new { @class = "text-danger" })
                </div>
                <div class="col-lg-3 col-md-3 col-xs-12 form-group">
                    <label>Fecha de Expedicion</label>
                    @Html.TextBoxFor(x => x.Infraccion.DateCreated, new { @class = "form-control text-capitalize" })
                    @Html.ValidationMessageFor(x => x.Infraccion.DateCreated, "", new { @class = "text-danger" })
                </div>
                <div class="col-lg-3 col-md-3 col-xs-12 form-group">
                    <label>Hora</label>
                    <input class="form-control text-capitalize" type="text" />
                </div>
                <div class="clearfix"></div>
                <div class="text-center">
                    <h5>INFRACIONES</h5>
                </div>
                @foreach (var t in Model.InfraccionTypes)
                {
                    <div class="col-lg-4 col-md-4 col-xs-6 form-group">
                        <input class="checkbox-inline" type="checkbox" value="@t.Id" name="InfractionTypesSelected" /> @t.TipoDeInfraccionName
                    </div>
                }
                <div class="col-lg-12 col-md-12 col-xs-12 form-group">
                    <label>Otro Concepto</label>
                    @Html.TextBoxFor(x => x.Infraccion.OtherConcept, new { @class = "form-control text-capitalize" })
                    @Html.ValidationMessageFor(x => x.Infraccion.OtherConcept, "", new { @class = "text-danger" })                
                </div>
                <div class="col-lg-12 col-md-12 col-xs-12 form-group">
                    <label>Foto de Prueba</label>
                    @*<input class="form-control" type="file" id="file1" name="file1" multiple />*@
                    <input class="form-control" type="file" multiple="multiple" id="file1" name="images" />

                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-lg btn-primary btn-block" value="Someter Infracción">
                </div>
            </form>
        </div>
    </div>
</div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VialidadSystem/Views/Infraccions/InfraccionConfirmacion.cshtml
@model AutoShopSystemManagement.Data.Dtos.InfraccionDetailDto

@{
    ViewBag.Title = "InfraccionConfirmacion";
    Layout = "~/Views/Shared/_LayoutSystem.cshtml";
}

<h2>Infraccion Confirmada</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <label>Nombre: </label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Infraccion.Persona.FirstName)
        </dd>

        <dt>
            <label>Marca del vehículo: </label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Infraccion.VehicleBrand)
        </dd>

        <dt>
            <label>No. de Placa:</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Infraccion.Placa)
        </dd>

        <dt>
            <label>Color de Vehículo:</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Infraccion.VehicleColor)
        </dd>

        <dt>
            <label>Año de Vehículo:</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Infraccion.VehicleYear)
        </dd>

        <dt>
            <label>Modelo de Vehículo:</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Infraccion.VehicleModel)
        </dd>

        <dt>
            <label>Lugar de la infracción:</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Infraccion.Ubicacion)
        </dd>

        <dt>
            <label>Fecha de la infracción:</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Infraccion.DateCreated)
        </dd>
        <dt>
            <label>Infracciones cometidas:</label>
        </dt>
        <dd>
            <ul>
                @foreach (var i in Model.Infracciones)
                {
                    <li>
                        @i
                    </li>
                }
            </ul>
        </dd>
        
        

        <dt>
            <label>Otro concepto:</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Infraccion.OtherConcept)
        </dd>

    </dl>
</div>

VialidadSystem/Views/Infraccions/ListarConceptos.cshtml
@model IEnumerable<AutoShopSystemManagement.Data.Entities.TipoDeInfraccion>

@{
    ViewBag.Title = "ListarConceptos";
    Layout = "~/Views/Shared/_LayoutSystem.cshtml";
}

<h2>ListarConceptos</h2>

<p>
    @Html.ActionLink("Create New", "AgregarTipoInfraccion", null,new   {@class= "btn btn-primary" })
</p>

<div class="row">
    <div class="col-lg-1 col-md-1 col-xs-1"><span class="text-center">No#</span></div>
    <div class="col-lg-6 col-md-6 col-xs-6"><h5 class="text-center">Tipo de Infracción</h5></div>
    <div class="col-lg-2 col-md-2 col-xs-2"><h5 class="text-center">Multiplicador</h5></div>
    <div class="col-lg-2 col-md-2 col-xs-2"><h5 class="text-center">Costo</h5></div>
</div>
@foreach (var item in Model) {    
<div class="row">
        <div class="col-lg-1 col-md-1 col-xs-1"><span class="text-center">@item.Id</span></div>
        <div class="col-lg-6 col-md-6 col-xs-6"><span class="text-center">@item.TipoDeInfraccionName</span></div>
        <div class="col-lg-2 col-md-2 col-xs-2"><spam class="text-center">@item.Multiplicador</spam></div>
    <div class="col-lg-2 col-md-2 col-xs-2"><spam class="text-center">@(item.Multiplicador*50)</spam></div>
    </div>
}

VialidadSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html ng-app="app">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Vialidad</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)  
    <link href="~/Content/style_comparisonreceiptdesign.css" rel="stylesheet" />
    <link href="~/Content/Main.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">   
</body>
</html>

VialidadSystem/Views/Shared/_LayoutSystem.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
    <head>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
        <link href="~/Content/style_comparisonreceiptdesign.css" rel="stylesheet" />
        <link href="~/Content/Main.css" rel="stylesheet" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    </head>
    <body>
        <div class="container-fluid display-table" ng-controller="navBarController">
            <div class="row display-table-row">
                <div class="col-md-2 col-sm-1 hidden-xs display-table-cell v-align box" id="navigation">
                    <div class="logo">
                        <a hef="home.html">
                            <img src="/Content/Images/logotam.png" alt="merkery_logo" class="hidden-xs hidden-sm">
                            <img src="/Content/Images/logotam.png" alt="merkery_logo" class="visible-xs visible-sm circle-logo">
                        </a>
                    </div>
                    <div class="navi">
                        <ul>
                            <li class="active"><a href="#/dashboard"><i class="fa fa-home" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Inicio</span></a></li>
                            <li><a href="/#/infraccion"><i class="fa fa-file-alt" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Infraccion</span></a></li>
                            <li><a href="@Url.Action("ListarConceptos","Infraccions")"><i class="fa fa-archive" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Conceptos</span></a></li>
                            <li><a href="#"><i class="fa fa-user" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Calender</span></a></li>
                            <li><a href="#"><i class="fa fa-calendar" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Users</span></a></li>
                            <li><a href="#"><i class="fa fa-cog" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Setting</span></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-10 col-sm-11 display-table-cell v-align">
                    <!--<button type="button" class="slide-toggle">Slide Toggle</button> -->
                    <div class="row">
                        <header>
                            <div class="col-md-7">
                                <nav class="navbar-default pull-left">
                                    <div class="navbar-header">
                                        <button type="button" class="navbar-toggle collapsed" data-toggle="offcanvas" data-target="#side-menu" aria-expanded="false">
                                            <span class="sr-only">Toggle navigation</span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                        </button>
                                    </div>
                                </nav>
                            </div>
                            <div class="col-md-5">
                                <div class="header-rightside">
                                    <ul class="list-inline header-top pull-right">
                                        <li class="hidden-xs"><a href="#" class="add-project" data-toggle="modal" data-target="#add_project">Add Project</a></li>
                                        <li><a href="#"><i class="fa fa-envelope" aria-hidden="true"></i></a></li>
                                        <li>
                                            <!--<a href="#" class="icon-info">
                                                <i class="fa fa-bell" aria-hidden="true"></i>
                                                <span class="label label-primary">3</span>
                                            </a>-->
                                        </li>
                                        <li class="dropdown">
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                                <img src="/Content/Images/userIcon.png" alt="user">
                                                <b class="caret"></b>
                                            </a>
                                            <ul class="dropdown-menu">
                                                <li>
                                                    <div class="navbar-content">
                                                        <span>JS Krishna</span>
                                                        <p class="text-muted small">
                                                            me@jskrishna.com
                                                        </p>
                                                        <div class="divider">
                                                        </div>
                                                        <a href="#" class="view btn-sm active">View Profile</a>
                                                    </div>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </header>
                    </div>
                    @RenderBody()
                </div>
            </div>
        </div>
    </body>
</html>